### ISSUE TITLE
keylogger not working

### ISSUE THREAD

**Issue by assafd** [Y4hL/PyDoor#3]
76.149.26.69> --k start
Keylogger ImportError

it occurs also if I running it native as py extension

**Comment by Y4hL** [comment]
Try Importing it in the python interpreter and see what the error is

**Comment by assafd** [comment]
Sorry, I did not understand if a module is missing from the file - it should not run - but show me an error and it does not display an error in executing

**Comment by Y4hL** [comment]
I made a failsafe, so if for any reason the import fails, the client on the target machine still runs

**Comment by assafd** [comment]
OK, Which module is this?

**Comment by Y4hL** [comment]
You can run ´pip install -r requirements.txt´ and it installs everything necessary

**Comment by assafd** [comment]
Work Thanks!

**Comment by Zazudoka** [comment]
Hi everyone, I've had this problem few moments ago, but all necessary packages were installed. The Listener from line 'from pynput.keyboard import Listener' wasn't imported correctly when executable was made by pyinstaller. The answer to this problem was to downgrade pynput module to lower version as it's said in this thread: https://stackoverflow.com/questions/67287580/py-to-exe-pyinstaller-import-errors . Hope it helps.
